name: 'Nhost Deploy'
description: 'Deploys an Nhost Project to app.nhost.io'
inputs:
  subdomain:
    description: 'Nhost subdomain'
    required: true
  git_ref:
    description: 'Git ref to deploy. Defaults to github.sha if available, otherwise github.ref'
    required: false
  message:
    description: 'Deploy message. Defaults to github.event.head_commit.message if available, otherwise github.event_name'
    required: false
  user:
    description: 'User that triggered the deploy. Defaults to github.actor'
    required: false
  user_avatar_url:
    description: 'User avatar URL. Defaults to https://github.com/{{ github.actor }}.png'
    required: false
  timeout:
    description: 'Timeout in seconds'
    required: false
    default: '300'
runs:
  using: "composite"
  steps:
    - name: Set variables
      shell: bash
      run: |
        if [ "${{ inputs.git_ref }}" != "" ]; then
          echo "git_ref=${{ inputs.git_ref }}" >> $GITHUB_OUTPUT
        elif [ "${{ github.sha }}" != "" ]; then
          echo "git_ref=${{ github.sha }}" >> $GITHUB_OUTPUT
        else
          echo "git_ref=${{ github.ref }}" >> $GITHUB_OUTPUT
        fi

        if [ "${{ inputs.message }}" != "" ]; then
          echo "message=${{ inputs.message }}" >> $GITHUB_OUTPUT
        elif [ "${{ github.event.head_commit.message }}" != "" ]; then
          echo "message=${{ github.event.head_commit.message }}" >> $GITHUB_OUTPUT
        elif [ "${{ github.event.workflow_run.head_commit.message }}" != "" ]; then
          echo "message=${{ github.event.workflow_run.head_commit.message }}" >> $GITHUB_OUTPUT
        else
          echo "message=${{ github.event.name }}" >> $GITHUB_OUTPUT
        fi

        if [ "${{ inputs.user }}" != "" ]; then
          echo "user=${{ inputs.user }}" >> $GITHUB_OUTPUT
          export ACTOR="${{ inputs.user }}"
        else
          echo "user=${{ github.actor }}" >> $GITHUB_OUTPUT
          export ACTOR="${{ github.actor }}"
        fi

        if [ "${{ inputs.user_avatar_url }}" != "" ]; then
          echo "user_avatar_url=${{ inputs.user_avatar_url }}" >> $GITHUB_OUTPUT
        else
          echo "user_avatar_url=https://github.com/$ACTOR.png" >> $GITHUB_OUTPUT
        fi

    - name: Deploy
      shell: bash
      run: |
        nhost deployments new \
          --subdomain "${{ inputs.subdomain }}" \
          --ref "${{ steps.set-variables.outputs.git_ref }}" \
          --message "${{ steps.set-variables.outputs.message }}" \
          --user "${{ steps.set-variables.outputs.user }}" \
          --user-avatar-url "${{ steps.set-variables.outputs.user_avatar_url }}" \
          --timeout "${{ inputs.timeout }}s" \
          --follow
